ALTER TABLE casos_de_covid RENAME TO caso_de_covid;
ALTER TABLE caso_de_covid RENAME COLUMN `evolucao_ID` to `fk_Evolucao_ID`;
ALTER TABLE bairro RENAME COLUMN `cod_rp` to `fk_Regiao_de_Planejamento_cod_rp`;
ALTER TABLE bairro RENAME COLUMN `codra` to `fk_Regiao_Administrativa_codra`;
ALTER TABLE bairro RENAME COLUMN `codra` to `fk_Regiao_Administrativa_codra`;
ALTER TABLE bairro RENAME COLUMN `codra` to `fk_Regiao_Administrativa_codra`;
ALTER TABLE Unidades_de_Saude RENAME COLUMN `codbairro` to `fk_Bairro_codbairro`;
ALTER TABLE Casos_de_COVID ADD CONSTRAINT FK_Caso_de_COVID_2 FOREIGN KEY (fk_Evolucao_ID) REFERENCES Evolucao (ID) ON DELETE CASCADE;
ALTER TABLE Bairro ADD CONSTRAINT FK_Bairro_2 FOREIGN KEY (fk_Regiao_Administrativa_codra) REFERENCES Regiao_Administrativa (codra) ON DELETE RESTRICT;
ALTER TABLE Bairro ADD CONSTRAINT FK_Bairro_3 FOREIGN KEY (fk_Regiao_de_Planejamento_cod_rp) REFERENCES Regiao_de_Planejamento (cod_rp) ON DELETE RESTRICT;
ALTER TABLE bairro ADD CONSTRAINT pk_Bairro PRIMARY KEY (codbairro);
ALTER TABLE Unidades_de_Saude ADD CONSTRAINT FK_Unidades_de_Saude_2 FOREIGN KEY (fk_Bairro_codbairro) REFERENCES bairro (codbairro) ON DELETE CASCADE;
ALTER TABLE Resida_Bairro_Caso_de_COVID_CEP ADD CONSTRAINT FK_Resida_Bairro_Caso_de_COVID_CEP_1 FOREIGN KEY (fk_Bairro_codbairro) REFERENCES Bairro (codbairro) ON DELETE NO ACTION;
ALTER TABLE caso_de_covid ADD CONSTRAINT pk_Caso_de_Covid PRIMARY KEY (ID);
ALTER TABLE Resida_Bairro_Caso_de_COVID_CEP ADD CONSTRAINT FK_Resida_Bairro_Caso_de_COVID_CEP_2 FOREIGN KEY (fk_Caso_de_COVID_ID) REFERENCES Caso_de_COVID (ID) ON DELETE NO ACTION;
ALTER TABLE Resida_Bairro_Caso_de_COVID_CEP ADD CONSTRAINT FK_Resida_Bairro_Caso_de_COVID_CEP_3 FOREIGN KEY (fk_CEP_ID) REFERENCES CEP (ID) ON DELETE NO ACTION;